export enum PermissionEnum {
  INVENTORY_MANAGE = 'INVENTORY_MANAGE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_VIEW = 'ORDER_VIEW',
  PERMISSION_MANAGE = 'PERMISSION_MANAGE',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  ROLE_MANAGE = 'ROLE_MANAGE',
  USER_MANAGE = 'USER_MANAGE',
}
